import type { Candidate, DashboardSnapshot, Order } from "@/lib/types";

const at = "2026-08-31T09:32:17Z";

const equity = [
  ["2026-01-02", 100000, 0],
  ["2026-02-02", 101240, -0.004],
  ["2026-03-02", 100680, -0.009],
  ["2026-04-01", 102360, -0.003],
  ["2026-05-01", 101940, -0.006],
  ["2026-06-01", 103820, -0.002],
  ["2026-07-01", 102980, -0.01],
  ["2026-08-28", 104230, -0.001],
  ["2026-08-31", 104180, -0.0015],
].map(([date, equityValue, drawdown]) => ({
  date: String(date),
  equity: Number(equityValue),
  drawdown: Number(drawdown),
}));

function placeholderOrder(symbol: string, confidence: number, maxLoss: number, thesis: string): Order {
  return {
    symbol,
    contracts: 1,
    limitPrice: null,
    clientOrderId: `sx-demo-${symbol.toLowerCase()}-093217`,
    maxLoss,
    definedRisk: true,
    confidence,
    thesis,
    structure: "put_credit_spread",
    resolution: "placeholder",
    executable: false,
    legs: [
      { symbol: `${symbol}_OCC_PLACEHOLDER`, side: "short", ratio: 1, type: "put", delta: 0.2, dteOffset: 0, resolved: false },
      { symbol: `${symbol}_OCC_PLACEHOLDER`, side: "long", ratio: 1, type: "put", delta: 0.1, dteOffset: 0, resolved: false },
    ],
  };
}

const candidates: Candidate[] = [
  {
    ticker: "SPY",
    company: "SPDR S&P 500 ETF Trust",
    sector: "Index ETF",
    iv: 0.236,
    hv: 0.166,
    ivRv: 1.42,
    ivRank: 0.81,
    price: 641.82,
    avgDollarVolume: 12_800_000_000,
    updatedAt: at,
    critic: {
      ticker: "SPY",
      decision: "APPROVED",
      confidence: 87,
      regimeSummary: "Credit conditions are contained and financial conditions remain broadly neutral.",
      thesis:
        "Implied volatility remains elevated against 20-day realised volatility while the independent VIX/RV signal confirms premium richness. The defined-risk structure maintains a controlled loss profile.",
      riskFactors: [
        "Index-level event risk can widen spreads abruptly.",
        "Premium selling remains exposed to a sharp downside move.",
      ],
      suggestedSizeMultiplier: 0.9,
    },
    risk: "APPROVED",
    analystConsensus: null,
    insiderMspr: null,
    headlines: [
      "US equities hold near record levels as volatility remains elevated.",
      "Options markets price a wider near-term range into macro data.",
    ],
    order: placeholderOrder("SPY", 87, 1800, "IV/RV and index-volatility confirmation passed."),
  },
  {
    ticker: "QQQ",
    company: "Invesco QQQ Trust",
    sector: "Index ETF",
    iv: 0.274,
    hv: 0.204,
    ivRv: 1.34,
    ivRank: 0.74,
    price: 572.1,
    avgDollarVolume: 8_600_000_000,
    updatedAt: at,
    critic: {
      ticker: "QQQ",
      decision: "APPROVED",
      confidence: 78,
      regimeSummary: "Macro indicators are stable, though technology concentration remains a relevant risk.",
      thesis:
        "Volatility premium clears the configured threshold and the setup remains defined-risk. Confidence is reduced for technology-sector concentration.",
      riskFactors: ["Technology concentration can amplify index drawdowns."],
      suggestedSizeMultiplier: 0.75,
    },
    risk: "APPROVED",
    analystConsensus: null,
    insiderMspr: null,
    headlines: [
      "Nasdaq volatility premium stays above realised volatility.",
      "Technology options demand holds firm.",
    ],
    order: placeholderOrder("QQQ", 78, 1500, "IV/RV premium is sufficient after confidence adjustment."),
  },
  {
    ticker: "IWM",
    company: "iShares Russell 2000 ETF",
    sector: "Index ETF",
    iv: 0.298,
    hv: 0.221,
    ivRv: 1.35,
    ivRank: 0.69,
    price: 218.44,
    avgDollarVolume: 4_200_000_000,
    updatedAt: at,
    critic: {
      ticker: "IWM",
      decision: "APPROVED",
      confidence: 71,
      regimeSummary: "Small-cap financial conditions are stable but remain more sensitive to rate path surprises.",
      thesis: "IV/RV clears the gate after liquidity checks. Size is reduced for higher realised-vol noise.",
      riskFactors: ["Small-cap liquidity can deteriorate faster than large-cap indices."],
      suggestedSizeMultiplier: 0.6,
    },
    risk: "APPROVED",
    analystConsensus: null,
    insiderMspr: null,
    headlines: ["Russell 2000 implied vol remains rich versus recent realised moves."],
    order: placeholderOrder("IWM", 71, 1200, "Index put vertical cleared liquidity floor."),
  },
  {
    ticker: "AAPL",
    company: "Apple Inc.",
    sector: "Technology",
    iv: 0.312,
    hv: 0.218,
    ivRv: 1.43,
    ivRank: 0.9,
    price: 234.12,
    avgDollarVolume: 10_100_000_000,
    updatedAt: at,
    critic: {
      ticker: "AAPL",
      decision: "REJECTED",
      confidence: 91,
      regimeSummary: "Macro conditions do not prevent a trade, but issuer-specific event risk dominates.",
      thesis:
        "The volatility premium is attractive, but recent earnings-related headlines indicate a scheduled jump-risk window that violates the critic policy.",
      riskFactors: [
        "Earnings-related headline detected within the restricted window.",
        "Single-name event risk is not approved for unattended execution.",
      ],
      suggestedSizeMultiplier: 0.5,
    },
    risk: "PENDING",
    analystConsensus: 1.2,
    insiderMspr: -12.4,
    headlines: [
      "Apple prepares to report quarterly results this week.",
      "Analysts update estimates ahead of earnings.",
    ],
  },
  {
    ticker: "NVDA",
    company: "NVIDIA Corporation",
    sector: "Technology",
    iv: 0.482,
    hv: 0.356,
    ivRv: 1.35,
    ivRank: 0.72,
    price: 178.56,
    avgDollarVolume: 28_400_000_000,
    updatedAt: at,
    critic: {
      ticker: "NVDA",
      decision: "REJECTED",
      confidence: 84,
      regimeSummary: "Broad risk appetite is constructive, but single-name concentration risk is elevated.",
      thesis: "Premium is rich, yet gap risk and position concentration rules reject unattended single-name premium selling here.",
      riskFactors: ["Elevated single-name gap risk.", "Sector concentration would breach configured guidance."],
      suggestedSizeMultiplier: 0.4,
    },
    risk: "HALTED",
    analystConsensus: 1.5,
    insiderMspr: 4.2,
    headlines: ["Semiconductor options remain active into product-cycle headlines."],
  },
  {
    ticker: "MSFT",
    company: "Microsoft Corporation",
    sector: "Technology",
    iv: 0.268,
    hv: 0.201,
    ivRv: 1.33,
    ivRank: 0.61,
    price: 512.3,
    avgDollarVolume: 9_800_000_000,
    updatedAt: at,
    critic: {
      ticker: "MSFT",
      decision: "PENDING",
      confidence: 66,
      regimeSummary: "Macro backdrop is acceptable; company context enrichment is incomplete.",
      thesis: "IV/RV clears the first gate, but analyst and insider context are insufficient for an unattended decision.",
      riskFactors: ["Incomplete company-context enrichment."],
      suggestedSizeMultiplier: 0.55,
    },
    risk: "UNAVAILABLE",
    analystConsensus: null,
    insiderMspr: null,
    headlines: ["Cloud demand commentary remains mixed across large-cap software peers."],
  },
  {
    ticker: "META",
    company: "Meta Platforms Inc.",
    sector: "Technology",
    iv: 0.341,
    hv: 0.252,
    ivRv: 1.35,
    ivRank: 0.77,
    price: 721.08,
    avgDollarVolume: 7_500_000_000,
    updatedAt: at,
    critic: {
      ticker: "META",
      decision: "REJECTED",
      confidence: 73,
      regimeSummary: "Financial conditions are stable; event calendar risk is material.",
      thesis: "Premium richness is real, but an upcoming product/event window fails the critic earnings-adjacent policy.",
      riskFactors: ["Event-window restriction.", "Single-name jump risk."],
      suggestedSizeMultiplier: 0.45,
    },
    risk: "PENDING",
    analystConsensus: 1.1,
    insiderMspr: 2.1,
    headlines: ["Options markets price elevated near-term event risk in communication services."],
  },
  {
    ticker: "AMZN",
    company: "Amazon.com Inc.",
    sector: "Consumer Discretionary",
    iv: 0.329,
    hv: 0.246,
    ivRv: 1.34,
    ivRank: 0.7,
    price: 228.9,
    avgDollarVolume: 11_200_000_000,
    updatedAt: at,
    critic: {
      ticker: "AMZN",
      decision: "APPROVED",
      confidence: 74,
      regimeSummary: "Macro conditions support defined-risk premium selling with reduced size.",
      thesis: "Chain IV/RV and liquidity thresholds clear. Confidence is moderated for retail-sensitive gap risk.",
      riskFactors: ["Retail-sensitive gap risk around discretionary demand surprises."],
      suggestedSizeMultiplier: 0.65,
    },
    risk: "APPROVED",
    analystConsensus: 1.3,
    insiderMspr: -3.1,
    headlines: ["E-commerce peers show elevated implied ranges versus recent realised volatility."],
    order: placeholderOrder("AMZN", 74, 1400, "Single-name vertical cleared earnings-distance filter."),
  },
];

export const mockSnapshot: DashboardSnapshot = {
  mode: "mock",
  asOf: at,
  warnings: [
    "Demo data is active. Backend adapter was not reached.",
    "Execution unavailable for unresolved option-leg previews.",
  ],
  pipeline: {
    id: "demo-20260831-093217",
    asOf: at,
    mode: "paper",
    finalState: "partial",
    errors: ["EXECUTE: option-leg resolution is incomplete for SPY."],
    stages: [
      { stage: "SCREEN", label: "Screen", result: "48 screened · 15 candidates", status: "complete" },
      { stage: "GATHER", label: "Gather", result: "12 enriched", status: "complete" },
      { stage: "CRITIQUE", label: "Critique", result: "4 approved · 3 rejected", status: "complete" },
      { stage: "FORM", label: "Form", result: "4 order previews", status: "complete" },
      { stage: "RISK", label: "Risk", result: "4 approved · 1 halted", status: "complete" },
      { stage: "EXECUTE", label: "Execute", result: "resolution incomplete", status: "blocked" },
    ],
    events: [
      { id: "1", timestamp: "09:32:11", stage: "SCREEN", ticker: "SPY", status: "complete", detail: "Entered candidate universe after IV/RV and liquidity filters." },
      { id: "2", timestamp: "09:32:11", stage: "SCREEN", ticker: "QQQ", status: "complete", detail: "Entered candidate universe after IV/RV and liquidity filters." },
      { id: "3", timestamp: "09:32:12", stage: "SCREEN", status: "info", detail: "No candidates is a valid outcome — 33 names failed liquidity or IV/RV gates." },
      { id: "4", timestamp: "09:32:13", stage: "GATHER", ticker: "SPY", status: "complete", detail: "Macro, company context, analyst and news inputs collected." },
      { id: "5", timestamp: "09:32:13", stage: "GATHER", ticker: "AAPL", status: "complete", detail: "Company context flagged an earnings-adjacent headline window." },
      { id: "6", timestamp: "09:32:15", stage: "CRITIQUE", ticker: "SPY", status: "complete", detail: "Approved at 87% confidence; premium remains rich versus realised volatility." },
      { id: "7", timestamp: "09:32:15", stage: "CRITIQUE", ticker: "AAPL", status: "blocked", detail: "Rejected — earnings-related jump risk violates unattended policy." },
      { id: "8", timestamp: "09:32:15", stage: "CRITIQUE", ticker: "NVDA", status: "blocked", detail: "Rejected — concentration and gap-risk policy." },
      { id: "9", timestamp: "09:32:16", stage: "FORM", ticker: "SPY", status: "complete", detail: "20Δ / 10Δ put vertical selected at target DTE." },
      { id: "10", timestamp: "09:32:16", stage: "FORM", ticker: "QQQ", status: "complete", detail: "20Δ / 10Δ put vertical selected at target DTE." },
      { id: "11", timestamp: "09:32:17", stage: "RISK", ticker: "SPY", status: "complete", detail: "Approved within premium-at-risk and position-slot limits." },
      { id: "12", timestamp: "09:32:17", stage: "RISK", ticker: "NVDA", status: "blocked", detail: "Halted — configured sector guidance would be breached if sized." },
      { id: "13", timestamp: "09:32:17", stage: "EXECUTE", ticker: "SPY", status: "blocked", detail: "Execution unavailable — option-leg resolution is incomplete." },
      { id: "14", timestamp: "09:32:17", stage: "EXECUTE", ticker: "QQQ", status: "info", detail: "Dry-run preview only. No brokerage order was submitted." },
    ],
  },
  candidates,
  portfolio: {
    nav: 104180,
    cash: 78420,
    aggregateUnrealizedPnl: 680,
    positions: [
      { symbol: "SPY260919P00620000", quantity: -1, averageEntryPrice: 7.2, unrealizedPnl: 420, protected: true, underlying: "SPY" },
      { symbol: "SPY260919P00600000", quantity: 1, averageEntryPrice: 3.4, unrealizedPnl: -140, protected: true, underlying: "SPY" },
      { symbol: "QQQ260919P00540000", quantity: -1, averageEntryPrice: 6.1, unrealizedPnl: 510, protected: false, underlying: "QQQ" },
      { symbol: "QQQ260919P00520000", quantity: 1, averageEntryPrice: 2.8, unrealizedPnl: -110, protected: true, underlying: "QQQ" },
    ],
    maxPositions: 10,
    premiumAtRisk: 1600,
    premiumAtRiskCap: 2084,
    remainingLeverage: 101_800,
    dailyDrawdown: 0.004,
    totalDrawdown: 0.015,
    hardHalt: null,
  },
  executions: [
    { symbol: "SPY", clientOrderId: "sx-demo-spy-093217", status: "unavailable", detail: "Execution unavailable — option-leg resolution is incomplete.", createdAt: at },
    { symbol: "QQQ", clientOrderId: "sx-demo-qqq-093217", status: "dry_run", detail: "Paper preview only. No order was submitted.", createdAt: at },
    { symbol: "AMZN", clientOrderId: "sx-demo-amzn-093217", status: "skipped_no_legs", detail: "Skipped — OCC legs could not be resolved from the option surface.", createdAt: at },
    { symbol: "IWM", clientOrderId: "sx-demo-iwm-091802", status: "duplicate", detail: "Already submitted today; duplicate was prevented.", createdAt: "2026-08-31T09:18:02Z" },
    { symbol: "SPY", clientOrderId: "sx-demo-spy-084401", status: "submitted", detail: "Paper order accepted by the broker API. Fill is not implied.", createdAt: "2026-08-31T08:44:01Z", orderId: "paper-ord-884401" },
    { symbol: "META", clientOrderId: "sx-demo-meta-083012", status: "error", detail: "Broker rejected the preview payload before submission.", createdAt: "2026-08-31T08:30:12Z" },
  ],
  performance: {
    name: "put_vertical_ivrv",
    source: "historical",
    period: "Kaggle EOD chains · SPY + QQQ · 2020–2022",
    sharpe: 0.92,
    maxDrawdown: -0.02,
    winRate: 0.68,
    trades: 102,
    profitFactor: 1.42,
    oosSharpe: 0.67,
    fragilityMedian: 0.94,
    equity,
    annualReturns: [
      { year: "2020", value: 0.034 },
      { year: "2021", value: 0.061 },
      { year: "2022", value: -0.015 },
    ],
    gateSweep: [
      { gate: "None", score: -0.78, deployed: false },
      { gate: "1.10", score: 0.2, deployed: false },
      { gate: "1.20", score: 0.77, deployed: false },
      { gate: "1.25", score: 0.96, deployed: false },
      { gate: "1.27", score: 1.11, deployed: true },
    ],
    fragility: [
      { parameter: "DTE −10", score: 0.85 },
      { parameter: "DTE +10", score: 1.01 },
      { parameter: "Short Δ −.05", score: 0.93 },
      { parameter: "Profit target", score: 0.96 },
      { parameter: "Slippage", score: 0.91 },
    ],
    comparisons: [
      { name: "put_vertical_ivrv", sharpe: 0.92, maxDrawdown: -0.02, trades: 102 },
      { name: "put_diagonal_ivrv_robust", sharpe: 1.01, maxDrawdown: -0.023, trades: 189 },
      { name: "index_condor_trend", sharpe: 0.97, maxDrawdown: -0.018, trades: 140 },
    ],
    tradePnL: [
      { bucket: "< −$1.0k", count: 4 },
      { bucket: "−$1.0k–−$0.5k", count: 8 },
      { bucket: "−$0.5k–0", count: 21 },
      { bucket: "0–$0.5k", count: 39 },
      { bucket: "$0.5k–$1.0k", count: 22 },
      { bucket: "> $1.0k", count: 8 },
    ],
    sampleComparisons: [
      {
        sample: "in_sample",
        label: "In sample · Kaggle SPY/QQQ 2020–2022",
        sharpe: 0.92,
        maxDrawdown: -0.02,
        trades: 102,
        detail: "Historical research after liquidity floor. Not live performance.",
      },
      {
        sample: "out_of_sample",
        label: "Out of sample · Dolt SPY 2019–2026",
        sharpe: 0.65,
        maxDrawdown: -0.028,
        trades: 148,
        detail: "Independent vendor / unseen years. Expect the lower figure live.",
      },
      {
        sample: "out_of_sample",
        label: "Out of sample · AAPL 2016–2023",
        sharpe: 0.49,
        maxDrawdown: -0.031,
        trades: 184,
        detail: "Unseen underlying. Not used to fit the deployed rule.",
      },
    ],
    generationHistory: [
      { evaluatedAt: "2026-08-28T23:38:00Z", generation: 0, strategy: "spy_put_credit_spread_ivr", underlyings: "SPY+QQQ", meanReturn: -0.009, meanSharpe: -0.13, maxDrawdown: -0.083, trades: 168, score: -1.18, note: "Hand-written baseline: 45 DTE put spread, IV rank gate." },
      { evaluatedAt: "2026-08-28T23:52:00Z", generation: 0, strategy: "idx_put_spread_ivrv_rich_v2", underlyings: "SPY+QQQ", meanReturn: 0.068, meanSharpe: 0.73, maxDrawdown: -0.032, trades: 141, score: 0.401, note: "Gen 0 winner of the IV/RV line." },
      { evaluatedAt: "2026-08-28T23:58:00Z", generation: 0, strategy: "diagonal_put_credit_80", underlyings: "SPY+QQQ", meanReturn: 0.035, meanSharpe: 0.85, maxDrawdown: -0.027, trades: 49, score: 0.749, note: "Gen 0 overall winner; only 49 trades." },
      { evaluatedAt: "2026-08-29T07:52:00Z", generation: 2, strategy: "idx_put_spread_ivrv_rich_v2_g1m0_g2m1", underlyings: "SPY+QQQ", meanReturn: 0.025, meanSharpe: 1.01, maxDrawdown: -0.011, trades: 59, score: 0.975, note: "Gen 2 winner; knife-edge DTE window." },
      { evaluatedAt: "2026-08-29T13:12:00Z", generation: 3, strategy: "vertical_ivrv_v0", underlyings: "SPY+QQQ", meanReturn: 0.067, meanSharpe: 1.14, maxDrawdown: -0.014, trades: 104, score: 1.089, note: "Gen 3 winner: re-centred to the 55–70 DTE plateau." },
      { evaluatedAt: "2026-08-29T15:20:00Z", generation: 4, strategy: "put_vertical_ivrv", underlyings: "SPY+QQQ", meanReturn: 0.067, meanSharpe: 1.15, maxDrawdown: -0.014, trades: 102, score: 1.112, note: "Require VIX/VXN to confirm the chain-derived vol gate.", deployed: true },
      { evaluatedAt: "2026-08-29T16:59:00Z", generation: 4, strategy: "put_vertical_ivrv", underlyings: "SPY+QQQ", meanReturn: 0.057, meanSharpe: 0.92, maxDrawdown: -0.02, trades: 102, score: 0.52, note: "Liquidity floor correction: require 25 contracts traded that day.", correction: true, deployed: true },
      { evaluatedAt: "2026-08-29T17:26:00Z", generation: 5, strategy: "put_vertical_singlename", underlyings: "AAPL", meanReturn: 0.144, meanSharpe: 0.9, maxDrawdown: -0.021, trades: 78, score: 0.838, note: "Single-name variant with earnings-distance filter." },
    ],
  },
  system: {
    api: { source: "Dashboard adapter", asOf: at, status: "unavailable", detail: "Showing demo fallback." },
    sources: [
      { source: "Alpaca", asOf: at, status: "refreshing", detail: "Paper account snapshot" },
      { source: "Finnhub", asOf: "2026-08-31T09:31:45Z", status: "fresh", detail: "Company context" },
      { source: "FRED", asOf: "2026-08-30T21:00:00Z", status: "delayed", detail: "Latest published macro close" },
      { source: "Kaggle", asOf: "2026-08-29T00:00:00Z", status: "fresh", detail: "Historical research dataset" },
      { source: "Dolt", asOf: "2026-08-29T00:00:00Z", status: "unavailable", detail: "Local option surface not available" },
    ],
    warnings: ["Configured sector and weekly-drawdown governance rules are not enforced by the current runtime."],
    governance: [
      { name: "Max position slots", value: "10", state: "enforced", detail: "Hard limit on concurrent option structures." },
      { name: "Premium at risk", value: "2% of NAV", state: "enforced", detail: "Sum of defined max losses versus account equity." },
      { name: "Daily drawdown halt", value: "5%", state: "enforced", detail: "Blocks new risk when daily mark-to-market drawdown trips." },
      { name: "Total drawdown halt", value: "20%", state: "enforced", detail: "Blocks new risk when peak-to-trough drawdown trips." },
      { name: "Sector concentration", value: "Configured", state: "configured_not_enforced", detail: "Present in configuration only; runtime does not enforce." },
      { name: "Weekly drawdown", value: "Configured", state: "configured_not_enforced", detail: "Present in configuration only; runtime does not enforce." },
      { name: "Stop-loss / take-profit", value: "Strategy research only", state: "configured_not_enforced", detail: "Backtest exit rules exist on strategy specs; live paper runtime does not auto-exit on SL/TP." },
      { name: "Paper trading only", value: "Required", state: "enforced", detail: "Live brokerage submission is outside V1 scope." },
    ],
  },
};
